name: pdrpulm
description: Pull Down to Refresh & Pull Up to Load More
version: 0.0.2
author: Ken <kenshao@gmail.com>
homepage: http://github.com/pedia/pdrpulm

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true